name: Download and Upload PDF

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Direct download URL (e.g. S3 or Dropbox)'
        required: true
        type: string
      filename:
        description: 'Filename to save as (e.g. file.pdf)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download file
      run: |
        echo "Downloading from: ${{ github.event.inputs.url }}"
        curl -L -o "${{ github.event.inputs.filename }}" "${{ github.event.inputs.url }}"
        ls -lh "${{ github.event.inputs.filename }}"

    - name: Commit file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add "${{ github.event.inputs.filename }}"
        git commit -m "Add file ${{ github.event.inputs.filename }}"
        git push
